name: Build Jemalloc RPM

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: ['almalinux:9', 'almalinux:8']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up AlmaLinux container and build Jemalloc
      run: |
        docker pull ${{ matrix.os }}
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ${{ matrix.os }} /bin/bash -c "
          if [[ ${{ matrix.os }} == 'almalinux:8' ]]; then
            DISTTAG='el8';
          else
            DISTTAG='el9';
          fi &&
          # Copy build script into the container
          cp /workspace/build-jemalloc.sh /tmp &&
          chmod +x /tmp/build-jemalloc.sh &&
          # Run build script
          /tmp/build-jemalloc.sh $DISTTAG
        "

    - name: Inspect RPM contents
      run: |
        rpm -qpl jemalloc-*.rpm

    - name: Set custom artifact name
      run: |
        if [[ ${{ matrix.os }} == 'almalinux:8' ]]; then
          echo "ARTIFACT_NAME=jemalloc-rpm-almalinux-8" >> $GITHUB_ENV
        else
          echo "ARTIFACT_NAME=jemalloc-rpm-almalinux-9" >> $GITHUB_ENV
        fi

    - name: Upload RPM
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: jemalloc-*.rpm
        if-no-files-found: warn
        compression-level: 0
        overwrite: false
