name: Build Jemalloc RPM

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: ['almalinux:9', 'almalinux:8']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up AlmaLinux container
      run: |
        docker pull ${{ matrix.os }}
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ${{ matrix.os }} /bin/bash -c "
          dnf install -y epel-release &&
          if [[ ${{ matrix.os }} == 'almalinux:8' ]]; then
            dnf config-manager --set-enabled powertools;
            DISTTAG='el8';
          else
            dnf config-manager --set-enabled crb;
            DISTTAG='el9';
          fi &&
          dnf groupinstall 'Development Tools' -y &&
          dnf install -y \
            wget \
            gcc \
            make \
            rpmdevtools \
            tar \
            curl \
            gnupg2 \
            libffi-devel \
            readline-devel \
            openssl-devel \
            zlib-devel \
            sqlite-devel \
            gcc-toolset-13-runtime --skip-broken &&
          
          # Import both GPG keys
          gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB ||
          (curl -sSL https://rvm.io/mpapis.asc | gpg2 --import && curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import) &&
          
          # Install RVM
          curl -sSL https://get.rvm.io | bash -s stable &&
          source /etc/profile.d/rvm.sh &&
          rvm reload &&

          # Function to install Ruby and fallback if necessary
          install_ruby() {
            RUBY_VERSION=$1
            echo 'Trying Ruby version' $RUBY_VERSION &&
            rvm install $RUBY_VERSION &&
            if rvm use $RUBY_VERSION --default; then
              echo 'Successfully installed and using Ruby version' $RUBY_VERSION &&
              rvm alias create default $RUBY_VERSION &&
              ruby -v &&
              gem install --no-document fpm
              return 0
            else
              echo 'Failed to install Ruby version' $RUBY_VERSION
              return 1
            fi
          }

          # Try installing Ruby 3.2.5, fallback to 3.1.6, and finally 3.0.7 if needed
          install_ruby 3.2.5 || install_ruby 3.1.6 || install_ruby 3.0.7

          # Ensure RVM is properly sourced after installation
          source /etc/profile.d/rvm.sh &&
          rvm use default &&
          ruby -v &&
          gem install fpm --no-document &&

          # Set the jemalloc version
          export JEMALLOCVER=5.3.0 &&

          # Build jemalloc
          JEMALLOC_LIBDIR=/usr/local/nginx-dep &&
          wget --max-redirect=20 https://github.com/jemalloc/jemalloc/archive/refs/tags/${JEMALLOCVER}.tar.gz -O jemalloc-${JEMALLOCVER}.tar.gz &&
          tar xzf jemalloc-${JEMALLOCVER}.tar.gz &&
          cd jemalloc-${JEMALLOCVER} &&

          # Configure and build jemalloc
          ./autogen.sh &&
          ./configure --prefix=${JEMALLOC_LIBDIR} --libdir=${JEMALLOC_LIBDIR}/lib --includedir=${JEMALLOC_LIBDIR}/include --with-version=${JEMALLOCVER}-0-g1 --with-jemalloc-prefix=je_ --with-malloc-conf='background_thread:true,dirty_decay_ms:1000,muzzy_decay_ms:1000' &&
          make -j$(nproc) build_lib_shared &&
          make -j$(nproc) build_lib_static &&

          # Install jemalloc to temporary directory
          rm -rf /tmp/installdir &&
          mkdir -p /tmp/installdir &&
          make install_lib_shared DESTDIR=/tmp/installdir &&
          make install_lib_static DESTDIR=/tmp/installdir &&
          make install_include DESTDIR=/tmp/installdir &&
          make install_bin DESTDIR=/tmp/installdir &&
          make install_lib_pc DESTDIR=/tmp/installdir &&

          # Create RPM using fpm
          if [ -f /usr/bin/xz ]; then
            FPMCOMPRESS_OPT='--rpm-compression xz';
          else
            FPMCOMPRESS_OPT='--rpm-compression gzip';
          fi &&
          echo '* $(date +"%a %b %d %Y") YourName <your-email> $JEMALLOCVER\n - jemalloc $JEMALLOCVER for custom Nginx' > jemalloc-${JEMALLOCVER}-changelog &&
          fpm -f -s dir -t rpm -n jemalloc-custom -v $JEMALLOCVER $FPMCOMPRESS_OPT --rpm-changelog jemalloc-${JEMALLOCVER}-changelog --rpm-summary 'jemalloc ${JEMALLOCVER} for custom Nginx' --rpm-dist $DISTTAG --description 'jemalloc ${JEMALLOCVER} for custom Nginx stacks' --url https://your-url.com --rpm-autoreqprov --rpm-rpmbuild-define '_build_id_links none' -C /tmp/installdir &&

          cp *.rpm /workspace/
        "

    - name: Inspect RPM contents
      run: |
        rpm -qpl jemalloc-*.rpm

    - name: Set custom artifact name
      run: |
        if [[ ${{ matrix.os }} == 'almalinux:8' ]]; then
          echo "ARTIFACT_NAME=jemalloc-rpm-almalinux-8" >> $GITHUB_ENV
        else
          echo "ARTIFACT_NAME=jemalloc-rpm-almalinux-9" >> $GITHUB_ENV
        fi

    - name: Upload RPM
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: jemalloc-*.rpm
        if-no-files-found: warn
        compression-level: 0
        overwrite: false
